version: '3.9'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./app:/var/www/html

  apache-httpd:
    build:
      context: .
      dockerfile: ./.docker/apache/Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm